### ISSUE TITLE
Delete file from S3 fails because of missing normalization

### ISSUE THREAD

**Issue by eitanshapiro** [thumbor-community/aws#140] opened 2020-01-21 17:28 UTC
Thumbor report successful delete while in practice the delete fails.

Branch Master
Also release 6.2.12

```
Copy/paste the result of the pip freeze command here. We'll be most interested in the versions of 

boto==2.49.0
boto3==1.11.6
botocore==1.14.6
thumbor==6.7.0
tornado==5.1.1
tornado-botocore==1.5.0
tornado-pyvows==0.6.1

### Configuration
TC_AWS_STORAGE_BUCKET = 'vo-thumbor-bucket' # S3 bucket for Storage
TC_AWS_STORAGE_ROOT_PATH = 'testDeleteImage' # S3 path prefix for Storage bucket
TC_AWS_REGION = 'us-east-1'

### Steps to reproduce

curl -i -H "Content-Type: image/png" -H "Slug: test.png" -XPOST http://localhost:8080/image --data-binary "@Avatar-85-256.png"

curl -i -XDELETE http://localhost:8080/image/1e98c320dd714290a33403e5c8e75b86/test.png

Delete is returning 204 but the file is not deleted in S3    :(

**Comment by eitanshapiro** [comment] 2020-01-21 17:29
Adding this code to s3_storage.py solves the issue

@return_future
def remove(self, path, callback=None):
    """
    Deletes data at path
    :param string path: Path to delete
    """
    super(Storage, self).remove(self._normalize_path(path), callback)

**Comment by eitanshapiro** [comment] 2020-01-21 17:33
Failed to deliver fix in branch :(
remote: Permission to thumbor-community/aws.git denied to eitanshapiro.

**Comment by kkopachev** [comment] 2020-01-23 16:52
@eitanshapiro you have to fork the repo, commit changes into your fork and then open PR into this repo. See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks

**Comment by eitanshapiro** [comment] 2020-02-24 13:23
What about moving to Python 3.0 ?
https://dev.to/scriptautomate/python-2-2020-end-of-life-eol-and-what-it-means-30p2

**Comment by kkopachev** [comment] 2020-02-24 22:53
@eitanshapiro waiting for thumbor to be python3 ready.

**Comment by Bladrak** [comment] 2022-12-07 14:16
Duplicate of #144

**Closed by Bladrak** 2022-12-07 14:16 UTC
